nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:3000']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization', 'X-Role', 'X-Customer-Id', 'Accept']
    expose_headers: ['Content-Type', 'Authorization']
    max_age: 3600
  paths:
    '^/': ~